name: Fastlane Update

on:
  schedule:
    # Every day at 3:04 UTC: https://crontab.guru/#4_3_*_*_*
    - cron: "4 3 * * *"

jobs:
  fastlane-update:
    # Do not run on forks.
    if: "github.repository == 'dasfoo/delern'"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      UPDATE_BRANCH: automated-update
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install dependencies"
        run: bundle install
      - name: "Fastlane Update"
        run: bundle exec fastlane update
      - name: "Check for changes and create/update PR"
        run: |
          git config url."https://api:${GITHUB_TOKEN?}@github.com/".insteadOf 'https://github.com/'

          if [ -n "$(git status --porcelain)" ]; then
            git checkout -b "${UPDATE_BRANCH?}"
            git add .
            git commit --message "[auto] update dependencies"
            git push -f origin HEAD

            brew install hub
            # If PR already exists, hub exits with code 1 (just like any other
            # failure). Ignore it.
            hub pull-request --no-edit || true
          else
            # Delete branch when there are no changes (e.g. to close PR), ignore
            # if it does not exist.
            git push origin ":${UPDATE_BRANCH?}" || true
          fi
